name: Check research template dev container functions

on:
  schedule:
    - cron: "18 8 * * *"
  workflow_dispatch:

jobs:
  dev-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout research-template repository
        uses: actions/checkout@v4
        with:
          repository: 'opensafely/research-template'

      - name: Checkout research-template-docker repository in subdirectory
        uses: actions/checkout@v4
        with:
          path: 'research-template/research-template-docker'
  
      - name: Build and run dev container task
        uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8 # v0.3.1900000349
        with:
          runCmd: ./research-template/research-template-docker/tests/dev_container.sh
