---
name: CI

env:
  IMAGE_NAME: research-template
  IMAGE_VERSION: v0
  PUBLIC_IMAGE_NAME: ghcr.io/opensafely-core/research-template
  REGISTRY: ghcr.io

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 12 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5  # v3.3.0
        # Lint the dockerfile before building
        with:
          failure-threshold: error
      - uses: "opensafely-core/setup-action@v1"
        with:
          install-just: true

      - name: Build docker image
        run: just build

      # This is a workaround to reclaim disk space.
      # Otherwise, the GitHub Actions runner can run out of space.
      - name: Prune docker builder
        run: docker builder prune --all --force

      - name: Save docker image
        run: |
          docker image save research-template-r-v1 | zstd --fast -o /tmp/research-template-r-v1.tar.zst
          docker image save research-template-r-v2 | zstd --fast -o /tmp/research-template-r-v2.tar.zst

      - name: Upload docker image
        uses: actions/upload-artifact@v7
        with:
            name: research-template-r-v1
            path: /tmp/research-template-r-v1.tar.zst
            # Disable compression; the file is already compressed
            compression-level: 0

      - name: Upload docker image
        uses: actions/upload-artifact@v7
        with:
            name: research-template-r-v2
            path: /tmp/research-template-r-v2.tar.zst
            # Disable compression; the file is already compressed
            compression-level: 0
            
  test-docker-image:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install just
      uses: "opensafely-core/setup-action@v1"
      with:
        install-just: true

    - name: Download Docker image
      uses: actions/download-artifact@v8
      with:
        name: research-template-r-v1
        path: /tmp/image

    - name: Import Docker image
      run: docker image load --input /tmp/image/research-template-r-v1.tar.zst

    - name: Test Python installation
      run: just test-python-install-v1

    - name: Test R Studio installation
      run: just test-rstudio-install-v1

    - name: Test packages
      run: just test-packages-v1

    - name: Test postCreate script
      run: just test-postcreate-script-v1

    - name: Download Docker image
      uses: actions/download-artifact@v8
      with:
        name: research-template-r-v2
        path: /tmp/image

    - name: Import Docker image
      run: docker image load --input /tmp/image/research-template-r-v2.tar.zst

    - name: Test Python installation
      run: just test-python-install-v2

    - name: Test R Studio installation
      run: just test-rstudio-install-v2

    - name: Test packages
      run: just test-packages-v2

    - name: Test postCreate script
      run: just test-postcreate-script-v2
